language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test:ci

after_success:
  - npm run coveralls
